version: 0.1
phases:
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Post Build completed on `date`
      - aws code deploy --application-name php-app  s3-location s3://marselino/source --region ap-southeast-3
